name: '[builder] CI for releases'

on:
    push:
        branches:
            - master
        tags:
            - Superalgos*

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Set env
            run: if [ "${GITHUB_REF#refs/*/}" = "master" ]; then echo "RELEASE_VERSION=latest"; else echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"; fi >> $GITHUB_ENV
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                buildx-version: latest
        -
            name: Build dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/amd64,linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file ./Docker/Dockerfile . \
                --tag ${{ secrets.DOCKER_USERNAME }}/superalgos:${RELEASE_VERSION}
